# SPDX-FileCopyrightText: 2021 Philipp Basler, Margarete Mühlleitner and Jonas Müller
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Unit tests

on:
  push:
    branches: [ master, matrix  ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
    

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
  ubuntu-tests-fullSetup:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - uses: actions/checkout@v3
      with:
          persist-credentials: false
          
    - name : installPackages on Ubuntu
      if: ${{ matrix.os }} == 'ubuntu-20.04'
      run : sudo apt-get update && sudo apt-get install --no-install-recommends --yes libgsl-dev libeigen3-dev libnlopt-dev libnlopt-cxx-dev libboost-all-dev
    
    - name: Install packages on Mac
      if: ${{ matrix.os }} == 'macos-latest'
      run: brew install eigen gsl nlopt boost libomp
      
      
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: cmake
      run: mkdir build && cd build && cmake .. 
    - name: make
      run: cd build && cmake --build . -j${{ steps.cpu-cores.outputs.count }}
    - name: Test
      run: cd build && ctest -j${{ steps.cpu-cores.outputs.count }} --output-on-failure
      


